spring:
  marvel-db:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/marvel?useSSL=false
    username: sai
    password: sai
  dc-db:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/dc?useSSL=false
    username: sai
    password: sai